

services:
  web:
    image: odoo:18
    depends_on:
      - db
    ports:
      - "8070:8069"
    volumes:
      - ./addons:/mnt/extra-addons # Carpeta para los módulos personalizados
      - ./odoo.conf:/etc/odoo/odoo.conf # Archivo de configuración de Odoo
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data 
      - ./odoo-data:/var/lib/odoo  
      - odoo-data-vol:/var/lib/odoo

volumes:
  pg_data:
  odoo-data-vol:
